export type Country = "CA" | "US" | "EU" | "AU";

export type Guild = {
  name: string;
  city: string;
  province: string;
  country: Country;
  website?: string;
  phone?: string;
  bio?: string;
};

export type Potter = {
  name: string;
  studio?: string;
  guild?: string;
  city: string;
  province: string;
  country: Country;
  website?: string;
  phone?: string;
  bio?: string;
  offersClasses?: boolean;
};

export type TeachingStudio = {
  name: string;
  city: string;
  province: string;
  country: Country;
  website?: string;
  phone?: string;
  bio?: string;
};

export type Supplier = {
  name: string;
  city: string;
  province: string;
  country: Country;
  website?: string;
  phone?: string;
  bio?: string;
};

export const guilds: Guild[] = [
  // British Columbia
  {
    name: "Potters Guild of British Columbia",
    city: "Vancouver",
    province: "British Columbia",
    country: "CA",
    website: "https://www.galleryofbcceramics.com",
    bio: "Established in 1955, one of Canada's oldest and largest ceramic arts organizations.",
  },
  {
    name: "BCPotters Guild",
    city: "Vancouver",
    province: "British Columbia",
    country: "CA",
    website: "https://www.bcpotters.com",
  },
  // Alberta
  {
    name: "Edmonton Potters' Guild",
    city: "Edmonton",
    province: "Alberta",
    country: "CA",
    website: "https://www.edmontonpottersguild.com",
    bio: "A pottery studio and guild community in Edmonton, Alberta.",
  },
  // Ontario
  {
    name: "Kawartha Potters' Guild",
    city: "Peterborough",
    province: "Ontario",
    country: "CA",
    website: "https://kawarthapottersguild.com",
    bio: "Home of the Canadian Ceramics Directory & Showcase, celebrating contemporary Canadian clay artists.",
  },
  {
    name: "Kingston Potters' Guild",
    city: "Kingston",
    province: "Ontario",
    country: "CA",
    website: "https://kingstonpottersguild.ca",
    bio: "Established in 1967, one of the oldest pottery guilds in Ontario.",
  },
  {
    name: "Mississauga Potters' Guild",
    city: "Mississauga",
    province: "Ontario",
    country: "CA",
    website: "https://mississaugapotters.com",
  },
  {
    name: "Pine Tree Potters' Guild",
    city: "Aurora",
    province: "Ontario",
    country: "CA",
    website: "https://www.pinetreepotters.ca",
  },
  {
    name: "Potters' Guild of Hamilton and Region",
    city: "Hamilton",
    province: "Ontario",
    country: "CA",
  },
  {
    name: "Burlington Potters' Guild",
    city: "Burlington",
    province: "Ontario",
    country: "CA",
    website: "https://burlingtonpottersguild.com",
    bio: "A vibrant group of artists welcoming all levels from complete beginner to professional, operating out of the Art Gallery of Burlington.",
  },
  {
    name: "Clay Studio Collective",
    city: "Athens",
    province: "Ontario",
    country: "CA",
    website: "https://claystudiocollective.com",
  },
  {
    name: "Clayworx",
    city: "London",
    province: "Ontario",
    country: "CA",
    website: "https://clayworx.ca",
  },
  {
    name: "Georgian Bay Pottery",
    city: "Collingwood",
    province: "Ontario",
    country: "CA",
    website: "https://georgianbaypottery.com",
  },
  {
    name: "Hill Potters' Guild",
    city: "Richmond Hill",
    province: "Ontario",
    country: "CA",
    website: "https://hillpotters.square.site",
  },
  {
    name: "North Bay Potters' Guild",
    city: "North Bay",
    province: "Ontario",
    country: "CA",
    website: "https://nbpottersguild.org",
  },
  {
    name: "Soffi Studio",
    city: "Windsor",
    province: "Ontario",
    country: "CA",
    website: "https://soffistudio.com",
  },
  {
    name: "Sudbury Basin Potters",
    city: "Sudbury",
    province: "Ontario",
    country: "CA",
  },
  {
    name: "Toronto Potters",
    city: "Toronto",
    province: "Ontario",
    country: "CA",
    website: "https://torontopotters.com",
    bio: "A volunteer collective of artists and art lovers supporting the local ceramics community since 1979, offering classes, workshops, juried exhibitions, and annual member sales in Toronto's west end.",
  },
  {
    name: "Waterloo Potters' Workshop",
    city: "Waterloo",
    province: "Ontario",
    country: "CA",
    website: "https://waterloopotters.ca",
    bio: "A non-profit cooperative operating since 1967 out of the historic Jacob Eby Farmhouse in Waterloo Park, offering classes, studio access, and community pottery sales.",
  },
  {
    name: "The Potters' Studio",
    city: "Scarborough",
    province: "Ontario",
    country: "CA",
    website: "https://thepottersstudio.ca",
    bio: "A member-run studio with 70 members and growing, offering wheel throwing, hand building, and open studio time in Scarborough.",
  },
  // Ontario (additional)
  {
    name: "Durham Potters' Guild",
    city: "Whitby",
    province: "Ontario",
    country: "CA",
    website: "https://www.durhampotters.com",
    bio: "Founded over 30 years ago for potters in the Durham Region. 26 active members ranging from emerging to highly experienced, with annual Spring and Christmas Show & Sales.",
  },
  // Ontario (additional)
  {
    name: "Ottawa Guild of Potters",
    city: "Ottawa",
    province: "Ontario",
    country: "CA",
    website: "https://ottawaguildofpotters.ca",
    bio: "A vibrant community of new, experienced, and professional potters in the Ottawa region, welcoming all skill levels.",
  },
  {
    name: "Deep River Potters' Guild",
    city: "Deep River",
    province: "Ontario",
    country: "CA",
    website: "https://www.deepriverpottersguild.ca",
    bio: "Celebrating over 70 years of fostering creativity and community spirit in the Ottawa Valley.",
  },
  // British Columbia (additional)
  {
    name: "Sea to Sky Potters' Guild",
    city: "Squamish",
    province: "British Columbia",
    country: "CA",
    website: "https://www.s2spottersguild.ca",
    bio: "A guild serving potters along the Sea to Sky corridor from West Vancouver to Whistler.",
  },
  // Nova Scotia
  {
    name: "Nova Scotia Potters Guild",
    city: "Halifax",
    province: "Nova Scotia",
    country: "CA",
    website: "https://nspotters.com",
    bio: "Celebrating and promoting the work of Nova Scotia's pottery community.",
  },
  // Prince Edward Island
  {
    name: "PEI Potters Studio Co-op",
    city: "Charlottetown",
    province: "Prince Edward Island",
    country: "CA",
    website: "https://peipottersstudio.ca",
    bio: "A cooperative pottery studio in the heart of Charlottetown, open to beginner and experienced ceramic artists alike.",
  },
  // Connecticut
  {
    name: "Connecticut Clay Guild",
    city: "Connecticut",
    province: "Connecticut",
    country: "US",
    website: "https://www.ctclayguild.com",
    bio: "Members include potters, sculptors, ceramic artists, studio owners, students, and educators from across Connecticut.",
  },
  // Colorado (additional)
  {
    name: "Northern Colorado Potters' Guild",
    city: "Fort Collins",
    province: "Colorado",
    country: "US",
    website: "https://www.nocopottersguild.org",
    bio: "Founded in 2005, a welcoming community of over eighty functional, sculptural, and creative clay artists.",
  },
  // Tennessee
  {
    name: "Memphis Potters' Guild",
    city: "Memphis",
    province: "Tennessee",
    country: "US",
    website: "https://www.thememphispottersguild.com",
    bio: "Committed to increasing public appreciation of quality craftsmanship through teaching, demonstrating, and exhibiting across the Memphis community.",
  },
  // Oregon
  {
    name: "Oregon Potters Association",
    city: "Portland",
    province: "Oregon",
    country: "US",
    website: "https://www.oregonpotters.org",
    bio: "An organization dedicated to educating, inspiring, and transforming lives through clay.",
  },
  // New Mexico
  {
    name: "New Mexico Potters and Clay Artists",
    city: "Santa Fe",
    province: "New Mexico",
    country: "US",
    website: "https://www.nmpotters.org",
    bio: "A virtual studio tour showcasing the work of contemporary ceramic artists across New Mexico.",
  },
  // Minnesota
  {
    name: "Northern Clay Center",
    city: "Minneapolis",
    province: "Minnesota",
    country: "US",
    website: "https://www.nccshop.org",
    bio: "A leading ceramics arts organization in Minneapolis supporting studio potters across Minnesota.",
  },
  // Colorado
  {
    name: "Colorado Potters Guild",
    city: "Denver",
    province: "Colorado",
    country: "US",
    website: "https://coloradopotters.org",
  },
  // New York
  {
    name: "Hudson River Potters",
    city: "Hudson Valley",
    province: "New York",
    country: "US",
    website: "https://www.hudsonriverpotters.net",
    bio: "An organization encompassing over 40 potters living and working in New York's Hudson Valley.",
  },
  // California
  {
    name: "Berkeley Potters Guild",
    city: "Berkeley",
    province: "California",
    country: "US",
    website: "https://berkeleypotters.com",
    bio: "A cooperative of professional local potters based in Berkeley.",
  },
  // Maryland
  {
    name: "Potters' Guild of Frederick",
    city: "Frederick",
    province: "Maryland",
    country: "US",
    website: "https://www.pottersguildoffrederick.com",
  },
  {
    name: "Potters Guild of Baltimore",
    city: "Baltimore",
    province: "Maryland",
    country: "US",
    website: "https://www.pottersguild.org",
  },
  // Michigan
  {
    name: "The Potters Guild of Ann Arbor",
    city: "Ann Arbor",
    province: "Michigan",
    country: "US",
    website: "https://www.pottersguild.net",
    bio: "A cooperative non-profit organization comprising over fifty member potters.",
  },
  // New Jersey
  {
    name: "Potters Guild of New Jersey",
    city: "New Jersey",
    province: "New Jersey",
    country: "US",
    website: "https://pottersguildnj.org",
    bio: "Founded in 1987 to promote the development of New Jersey's ceramic artists.",
  },
  // Virginia
  {
    name: "Blue Ridge Potters Guild",
    city: "Blue Ridge",
    province: "Virginia",
    country: "US",
    website: "https://www.blueridgepotters.com",
    bio: "Celebrating pottery and ceramic arts across Virginia.",
  },
  // Washington
  {
    name: "Spokane Potters' Guild",
    city: "Spokane",
    province: "Washington",
    country: "US",
    website: "https://spokanepottersguild.org",
    bio: "A non-profit, volunteer-based organization founded in 1977.",
  },
  // England (additional)
  {
    name: "London Potters",
    city: "London",
    province: "England",
    country: "EU",
    website: "https://londonpotters.com",
    bio: "Established in 1986, the only London-based society open to both professional and non-professional ceramicists, providing a platform for exchanging ideas.",
  },
  // England
  {
    name: "Craft Potters Association",
    city: "London",
    province: "England",
    country: "EU",
    website: "https://www.craftpotters.com",
    bio: "Founded in 1958, the national body representing studio potters and ceramic artists across the UK and Ireland, with over 300 members and a gallery in London opposite the British Museum.",
  },
  {
    name: "Northern Potters Association",
    city: "Northern England",
    province: "England",
    country: "EU",
    website: "https://www.northern-potters.co.uk",
    bio: "With over 800 members, the NPA supports studio pottery across northern England through exhibitions, workshops, a quarterly newsletter, and an annual Potters Camp.",
  },
  // Scotland
  {
    name: "Scottish Potters Association",
    city: "Scotland",
    province: "Scotland",
    country: "EU",
    website: "https://www.scottishpotters.org",
    bio: "Founded in 1974, the SPA promotes handmade pottery and ceramics across Scotland through exhibitions, workshops, a member directory, and an annual symposium.",
  },
  // Ireland
  {
    name: "Ceramics Ireland",
    city: "Ireland",
    province: "Ireland",
    country: "EU",
    website: "https://www.ceramicsireland.ie",
    bio: "Founded in 1977, Ceramics Ireland hosts exhibitions, workshops, and a biennial international festival with membership open to practitioners, students, and friends of ceramics.",
  },
  // France
  {
    name: "Henriot-Quimper",
    city: "Quimper",
    province: "France",
    country: "EU",
    website: "https://www.hb-henriot.com",
    bio: "One of France's oldest active potteries, founded in 1690, continuing the living tradition of hand-painted Breton faience decorated by skilled faïenciers with traditional regional motifs.",
  },
  // Netherlands
  {
    name: "European Ceramic Work Centre",
    city: "'s-Hertogenbosch",
    province: "Netherlands",
    country: "EU",
    website: "https://ekwc.nl",
    bio: "A prestigious international artist-in-residence and research centre where artists, designers, and architects from around the world work with full technical support and state-of-the-art facilities.",
  },
  // Denmark
  {
    name: "Guldagergaard International Ceramic Research Center",
    city: "Skælskør",
    province: "Denmark",
    country: "EU",
    website: "https://ceramic.dk",
    bio: "Founded in 1997, a world-leading international ceramics residency and research centre offering artist-in-residence stays, grant-funded programmes, and workshops for potters worldwide.",
  },
  // New South Wales
  {
    name: "The Australian Ceramics Association",
    city: "Sydney",
    province: "New South Wales",
    country: "AU",
    website: "https://australianceramics.com",
    bio: "The peak national body for Australian ceramics, connecting ceramicists across all states through membership, an open studios directory, the Journal of Australian Ceramics, and national events.",
  },
  // South Australia
  {
    name: "Studio Potters SA",
    city: "Adelaide",
    province: "South Australia",
    country: "AU",
    website: "https://www.studiopotters.com",
    bio: "A South Australian organisation providing classes, exhibition opportunities, and inclusion in Adelaide arts festivals for local ceramicists.",
  },
  // Western Australia
  {
    name: "Ceramic Arts Association of Western Australia",
    city: "Perth",
    province: "Western Australia",
    country: "AU",
    website: "https://www.ceramicartswa.asn.au",
    bio: "A not-for-profit organisation with over 120 WA ceramicists promoting handmade pottery and ceramic sculpture through exhibitions, workshops, and the biennial Members Selective Exhibition.",
  },
  // Western Australia (additional)
  {
    name: "Perth Studio Potters",
    city: "Perth",
    province: "Western Australia",
    country: "AU",
    website: "http://www.perthstudiopotters.org.au",
    bio: "A community of studio potters based in Perth, promoting handmade ceramics and ceramic arts across Western Australia.",
  },
  // Queensland
  {
    name: "Ceramic Arts Queensland",
    city: "Brisbane",
    province: "Queensland",
    country: "AU",
    website: "https://ceramicartsqld.org.au",
    bio: "Founded in Brisbane in 1968, CAQ fosters an inclusive ceramic arts community across Queensland through the biennial Siliceous Award for Ceramic Excellence, workshops, and member exhibitions.",
  },
];

export const potters: Potter[] = [
  // Alberta
  {
    name: "Heather",
    studio: "Pottery By Heather",
    city: "Bon Accord",
    province: "Alberta",
    country: "CA",
    website: "https://potterybyheather.com",
    bio: "Handmade pottery and functional art from a working studio just north of Edmonton. Open by appointment.",
  },
  {
    name: "Linh Ly",
    studio: "Starfishly Clay Works",
    city: "Calgary",
    province: "Alberta",
    country: "CA",
    website: "https://www.starfishlyclay.com",
    bio: "Limited edition, artisan hand-thrown pottery with a modern twist. Based in Calgary.",
  },
  {
    name: "Janet Grabner",
    studio: "Caracol Clay Studio",
    city: "East Coulee",
    province: "Alberta",
    country: "CA",
    website: "https://www.caracolclaystudio.com",
    bio: "Hand-built porcelain and stoneware in the Alberta Badlands, inspired by hoodoos, fossils, and the natural landscape around Drumheller.",
  },
  {
    name: "Kerry Tronnes",
    studio: "Mad Monkey Ceramic Studio",
    city: "Red Deer",
    province: "Alberta",
    country: "CA",
    website: "https://madmonkeystudio.ca",
    bio: "Hand-thrown and hand-built ceramics balancing sculptural presence with everyday function, defined by an obsession with colour, texture, and experimental glazes.",
  },
  {
    name: "Dawn Candy",
    studio: "Little Sister Pottery",
    city: "Red Deer",
    province: "Alberta",
    country: "CA",
    website: "https://www.littlesister.ca",
    bio: "Wheel-thrown ceramics inspired by rhythm, pattern, and landscape — referencing wind-whipped grasses, lacy leaf patterns, and the quiet drama of Prairie seasons.",
  },
  {
    name: "Connie Pike",
    studio: "Pike Studios",
    city: "High River",
    province: "Alberta",
    country: "CA",
    website: "https://pikestudios.com",
    bio: "Decorative and functional handcrafted pottery featuring distinctive patterns and whimsical pieces, made in High River.",
  },
  {
    name: "Moon Kim",
    studio: "MoonK Studio",
    city: "Edmonton",
    province: "Alberta",
    country: "CA",
    website: "https://moonkstudiopottery.com",
    bio: "Korean-influenced handmade pottery blending Korean style with Canadian inspiration, made in Edmonton.",
  },
  // British Columbia
  {
    name: "Mike Allegretti",
    studio: "Creek Clayworks",
    city: "Roberts Creek",
    province: "British Columbia",
    country: "CA",
    website: "https://creekclayworks.ca",
  },
  {
    name: "Zohra Bonnis",
    city: "Vancouver",
    province: "British Columbia",
    country: "CA",
    website: "https://www.zohrabonnis.com",
    bio: "A Canadian ceramic artist, curator, and founder of Z Gallery Arts in Vancouver whose practice is deeply rooted in tradition and guided by wabi-sabi philosophy.",
  },
  {
    name: "Elaine Brewer-White",
    city: "Langley",
    province: "British Columbia",
    country: "CA",
    website: "https://elainebrewerwhiteceramics.com",
  },
  {
    name: "Sharon Bussard Grove",
    city: "Sooke",
    province: "British Columbia",
    country: "CA",
    website: "https://sharonbussardgrove.ca",
  },
  {
    name: "Francis Chan",
    studio: "Potluck Ceramics",
    city: "Vancouver",
    province: "British Columbia",
    country: "CA",
    website: "https://potluckceramics.com",
  },
  {
    name: "Amy Li-Chuan Chang",
    city: "Vancouver",
    province: "British Columbia",
    country: "CA",
    website: "https://amychangceramics.com",
  },
  {
    name: "Larry Cohen",
    city: "Cortes Island",
    province: "British Columbia",
    country: "CA",
    website: "https://www.larrycohenceramics.ca",
  },
  {
    name: "Liz de Beer",
    studio: "Klaywerk Studio",
    city: "Gibsons",
    province: "British Columbia",
    country: "CA",
    website: "https://www.lizdebeer.com",
  },
  {
    name: "Anthony Dunlop",
    studio: "Antler Ceramics",
    city: "Vancouver",
    province: "British Columbia",
    country: "CA",
    website: "https://www.antlerceramics.com",
  },
  {
    name: "Connie Glover",
    studio: "Connie Glover Pottery",
    city: "Surrey",
    province: "British Columbia",
    country: "CA",
    website: "https://www.connieglover.com",
  },
  {
    name: "Lance Hall",
    studio: "Still Point Pottery",
    city: "Slocan Valley",
    province: "British Columbia",
    country: "CA",
    website: "https://www.stillpointpottery.ca",
  },
  {
    name: "Andrea Hoff",
    city: "Vancouver",
    province: "British Columbia",
    country: "CA",
    website: "https://www.andreahoff.com",
  },
  {
    name: "Pam Horner",
    city: "Gibsons",
    province: "British Columbia",
    country: "CA",
    website: "https://potterybypam.ca",
  },
  {
    name: "Robin Jenkins",
    studio: "Robin's Nest Pottery",
    city: "Tsawwassen",
    province: "British Columbia",
    country: "CA",
    website: "https://www.robinsnestpottery.com",
  },
  {
    name: "Diane Walters",
    studio: "eARTh Studios",
    city: "Nelson",
    province: "British Columbia",
    country: "CA",
    website: "https://earthstudiosonline.com",
  },
  {
    name: "Hillary Webb",
    city: "Vancouver",
    province: "British Columbia",
    country: "CA",
    website: "https://www.hillarywebb.ca",
  },
  {
    name: "Susan Whitham",
    studio: "MiraSol Studio",
    city: "Duncan",
    province: "British Columbia",
    country: "CA",
    website: "https://www.mirasolstudio.com",
  },
  {
    name: "Clare Wilkening",
    city: "Roberts Creek",
    province: "British Columbia",
    country: "CA",
    website: "https://www.clarewilkening.com",
  },
  {
    name: "Kate Metten",
    studio: "Kate Metten Ceramics",
    city: "Vancouver",
    province: "British Columbia",
    country: "CA",
    website: "https://www.katemetten.com",
    bio: "Wheel-thrown modernist pottery tableware glazed with hand-derived recipes from local materials. Studio on Main Street, Vancouver.",
  },
  {
    name: "Mary Fox",
    studio: "Mary Fox Pottery",
    city: "Ladysmith",
    province: "British Columbia",
    country: "CA",
    website: "https://maryfoxpottery.ca",
    bio: "Self-taught exploratory potter based in Ladysmith on Vancouver Island.",
  },
  {
    name: "Sarah Pike",
    studio: "Sarah Pike Pottery",
    city: "Fernie",
    province: "British Columbia",
    country: "CA",
    website: "https://www.sarahpikepottery.com",
    bio: "Full-time potter making functional slab-built pottery in a home studio on the edge of a ski town in Fernie, BC.",
  },
  {
    name: "Yuki Kianna",
    studio: "Yuki Kianna Studio",
    city: "Nelson",
    province: "British Columbia",
    country: "CA",
    website: "https://yukikiannastudio.com",
    bio: "Handmade functional pottery inspired by the BC wilderness and Kootenay Lake. Soft colours and whimsical elements woven into every piece.",
  },
  {
    name: "Cori Sandler",
    studio: "Cori Sandler Pottery",
    city: "Comox Valley",
    province: "British Columbia",
    country: "CA",
    website: "https://corisandler.com",
    bio: "Over 30 years of studio pottery inspired by the ocean, rain forests, and coastal mountains of Vancouver Island — functional, contemporary, and full of life.",
  },
  {
    name: "Briana Paulson",
    studio: "Love Co. Ceramics",
    city: "Kelowna",
    province: "British Columbia",
    country: "CA",
    website: "https://www.lovecoceramics.ca",
    bio: "Minimalist handmade pottery with hand-painted designs and natural clay textures that let the beauty of the material speak for itself.",
  },
  {
    name: "Julie MacKinnon",
    studio: "Julie MacKinnon Ceramics",
    city: "Salt Spring Island",
    province: "British Columbia",
    country: "CA",
    website: "https://juliemackinnonceramics.com",
    bio: "Fine porcelain and stoneware with graceful, architectural forms handcrafted on Salt Spring Island for everyday use and special occasions.",
  },
  {
    name: "Morgan Fraser",
    studio: "Studio Outyard",
    city: "Salt Spring Island",
    province: "British Columbia",
    country: "CA",
    website: "https://www.studio-outyard.com",
    bio: "Handcrafted goods made to last a lifetime, shaped with slow, intentional methods inspired by the natural landscape of Salt Spring Island.",
  },
  {
    name: "Normand Desrosiers",
    studio: "Salt Spring Pottery",
    city: "Salt Spring Island",
    province: "British Columbia",
    country: "CA",
    website: "http://saltspringpottery.ca",
    bio: "Handcrafted ceramic mugs, casserole dishes, and serving plates made from 100% Salt Spring Island clay.",
  },
  {
    name: "Peter Flanagan",
    studio: "Okanagan Pottery",
    city: "Peachland",
    province: "British Columbia",
    country: "CA",
    website: "https://www.okanaganpottery.com",
    bio: "Award-winning potter established in the Okanagan since 1968, creating hand-thrown work in collaboration with his wife and partner Daphne.",
  },
  // New Brunswick
  {
    name: "Tim Isaac",
    city: "New Horton",
    province: "New Brunswick",
    country: "CA",
    website: "https://timisaacpottery.com",
    bio: "Raku-fired clay incorporating seashells, rocks, and fossils gathered near the Bay of Fundy. Offers workshops from a studio in New Horton, NB.",
  },
  {
    name: "Krysta Oland",
    studio: "Morning Sun Pottery",
    city: "Harvey Station",
    province: "New Brunswick",
    country: "CA",
    website: "https://morningsunpottery.com",
    bio: "Functional pots for everyday use, handcrafted in Harvey Station. Juried member of the New Brunswick Crafts Council.",
  },
  // Ontario
  {
    name: "Karen Gray",
    studio: "The Potter's Studio & Gallery",
    city: "Huntsville",
    province: "Ontario",
    country: "CA",
    website: "https://thepottersstudio.com",
    bio: "Original Canadian Sgraffito pottery made in Muskoka. Gallery and working pottery studio in downtown Huntsville.",
  },
  {
    name: "Naomi Clement",
    studio: "Naomi Clement Ceramics",
    city: "Stratford",
    province: "Ontario",
    country: "CA",
    website: "https://naomiclement.com",
    bio: "Ceramic artist and workshop instructor creating functional ceramics from her home studio in Stratford, Ontario.",
  },
  {
    name: "Stainsby Studios",
    city: "Toronto",
    province: "Ontario",
    country: "CA",
    website: "https://stainsbystudios.com",
    bio: "Handmade modern ceramics made in Toronto.",
  },
  // Ontario — individual potters
  {
    name: "Megan Egerton",
    studio: "Meg's Pottering",
    city: "Ottawa",
    province: "Ontario",
    country: "CA",
    website: "https://www.megspottering.com",
    bio: "Uniquely crafted handmade ceramic pieces made to be both fun and functional, available in Ottawa.",
  },
  {
    name: "Kevin",
    studio: "Swampdog Ceramics",
    city: "Peterborough",
    province: "Ontario",
    country: "CA",
    website: "https://www.swampdogceramics.ca",
    bio: "Functional pottery for home and garden — wheel-thrown and slab-built pieces handmade in a home studio just west of Peterborough.",
  },
  {
    name: "Eva Mlcak",
    studio: "Queenston Pottery",
    city: "Niagara-on-the-Lake",
    province: "Ontario",
    country: "CA",
    website: "https://www.queenstonpottery.com",
    bio: "Handcrafted stoneware with distinctive hand-painted designs continuing a pottery legacy established in Niagara since 1978.",
  },
  {
    name: "Andrea DeKay",
    studio: "Flux Pottery",
    city: "London",
    province: "Ontario",
    country: "CA",
    website: "https://www.fluxpottery.ca",
    bio: "Timeless, well-crafted pottery in rich earthy colours designed for everyday use, made in Wortley Village, London.",
  },
  {
    name: "Marc Lemieux",
    studio: "Black Dog Pottery",
    city: "Kingston",
    province: "Ontario",
    country: "CA",
    website: "https://blackdogpottery.ca",
    bio: "Handmade porcelain and stoneware — functional and decorative — at a working studio and gallery in downtown Kingston.",
  },
  {
    name: "Brooke",
    studio: "Olive Tree Pottery",
    city: "Hamilton",
    province: "Ontario",
    country: "CA",
    website: "https://olivetreepottery.com",
    bio: "Handmade ceramic pieces inspired by the Great Lakes and Ontario's natural landscapes, made in a home studio in Hamilton.",
  },
  {
    name: "Scott Barnim",
    studio: "Scott Barnim Pottery",
    city: "Dundas",
    province: "Ontario",
    country: "CA",
    website: "https://scottbarnimpottery.com",
    bio: "Functional stoneware dinnerware and decorative pieces inspired by the Dundas Valley, plus reduced Islamic lustreware — one of few potters in North America practising the technique.",
  },
  {
    name: "Susan Card",
    studio: "DISH Gallery + Studio",
    city: "Toronto",
    province: "Ontario",
    country: "CA",
    website: "https://www.dishgalleryandstudio.com",
    bio: "Wheel-thrown porcelain and smoke-fired pottery decorated with motifs from nature, exploring colour, visual space, and the balance between sculptural and functional forms.",
  },
  {
    name: "Michelle Organ",
    studio: "Mima Ceramics",
    city: "Toronto",
    province: "Ontario",
    country: "CA",
    website: "https://mimaceramics.com",
    bio: "Handmade ceramics designed to be used and loved daily, drawing on everyday textures and blending traditional craftsmanship with contemporary design.",
  },
  {
    name: "Anne Gibson",
    studio: "Kalon Ceramics",
    city: "Toronto",
    province: "Ontario",
    country: "CA",
    website: "https://kalonceramics.ca",
    bio: "Thoughtfully made artisan stoneware pieces with original character, handmade in Toronto.",
  },
  {
    name: "Daniel Maxwell",
    studio: "Maxwell Pottery",
    city: "Mattawa",
    province: "Ontario",
    country: "CA",
    website: "https://maxwellpottery.com",
    bio: "Trained at Sheridan College, Daniel established Maxwell Pottery in 1991, creating functional hand-painted stoneware using wheel throwing, hand building, pressing, and slip casting with in-studio glazes.",
  },
  {
    name: "Pavlo Pottery",
    city: "Rockton",
    province: "Ontario",
    country: "CA",
    website: "https://pavlopottery.com",
    bio: "Functional one-of-a-kind pottery made in the small village of Rockton, Ontario, a short drive from Hamilton and Cambridge.",
  },
  {
    name: "Sandra Silberman",
    studio: "Dotti Potts",
    city: "Barrie",
    province: "Ontario",
    country: "CA",
    website: "https://dottipotts.com",
    bio: "Ceramic artist with over 30 years of experience creating functional and decorative handmade pieces that blend clean modern design with playful textures, patterns, and dots. Also offers pottery workshops and private clay parties.",
  },
  // Quebec
  {
    name: "Baie d'Urfé Potters' Guild",
    city: "Baie d'Urfé",
    province: "Quebec",
    country: "CA",
    website: "https://bdupottersguild.com",
  },
  // Quebec — individual potters
  {
    name: "Sophie Manessiez",
    studio: "Sophie Manessiez Ceramics",
    city: "Shefford",
    province: "Quebec",
    country: "CA",
    website: "https://sophiemanessiez.com/en/",
    bio: "Delicate porcelain sculptures with complex structures, shaped through the repetition of pure and simple forms in the Eastern Townships.",
  },
  {
    name: "Murai Ceramique",
    city: "Gatineau",
    province: "Quebec",
    country: "CA",
    website: "https://www.muraiceramique.com",
    bio: "Handmade pottery emphasising the beauty of the natural world, made and taught at a studio in the Gatineau Hills.",
  },
  {
    name: "Mie Kim",
    studio: "Studio Mie Kim",
    city: "Montreal",
    province: "Quebec",
    country: "CA",
    website: "https://miekimstudio.com",
    bio: "Handmade ceramics including tea cups, plates, and hand-carved Kurinuki Chawan pieces.",
  },
  {
    name: "Céline Fafard",
    studio: "Parceline Céramique",
    city: "Montreal",
    province: "Quebec",
    country: "CA",
    website: "https://parcelineceramique.com",
    bio: "Handmade pottery on the wheel from high-quality stoneware and porcelain. Studio open by appointment in Montreal.",
  },
  // Manitoba
  {
    name: "Michael Holroyd & Karen Thomas",
    studio: "Bunns Creek Pottery",
    city: "Winnipeg",
    province: "Manitoba",
    country: "CA",
    website: "https://www.bunnscreekpottery.ca",
    bio: "Handmade pottery for home and garden with a focus on eco-friendly practices, including seed starters, ollas, mugs, and functional tableware.",
  },
  {
    name: "Cheryl",
    studio: "Thistlewood Pottery Studio",
    city: "Whitemouth",
    province: "Manitoba",
    country: "CA",
    website: "https://thistlewood.ca",
    bio: "Wheel-thrown stoneware mugs, bowls, and small-batch functional pieces made in a rural Manitoba studio, shipped across Canada and the US.",
  },
  {
    name: "Crystal Nykoluk",
    city: "Winnipeg",
    province: "Manitoba",
    country: "CA",
    website: "https://www.crystalnykoluk.com",
    bio: "Ceramic artist and earthshaper living and working in Winnipeg.",
  },
  // Nova Scotia
  {
    name: "Sugarhouse Ceramic Co.",
    city: "Kentville",
    province: "Nova Scotia",
    country: "CA",
    website: "https://sugarhouseceramicco.com",
    bio: "Handmade ceramics inspired by the Atlantic Maritime, made in Kentville, Nova Scotia.",
  },
  {
    name: "Joan Bruneau",
    studio: "Nova Terra Cotta",
    city: "Lunenburg",
    province: "Nova Scotia",
    country: "CA",
    website: "https://joanbruneau.com",
    bio: "Established Nova Terra Cotta in Lunenburg in 1995. Work exhibited throughout North America and held in private and public collections.",
  },
  {
    name: "Toni Losey",
    city: "Dartmouth",
    province: "Nova Scotia",
    country: "CA",
    website: "https://www.toniloseypottery.com",
    bio: "Creates complex, highly saturated organic ceramic sculptures through the abstraction and reinterpretation of common plant life.",
  },
  {
    name: "Riverside Pottery",
    city: "Bear River",
    province: "Nova Scotia",
    country: "CA",
    website: "https://www.riversidepottery.ca",
    bio: "Handmade pottery made to be used and enjoyed — all pieces are microwave and dishwasher safe.",
  },
  {
    name: "Jessie Wright",
    studio: "JAW Pottery",
    city: "Halifax",
    province: "Nova Scotia",
    country: "CA",
    website: "https://jawpottery.com",
    bio: "Self-taught potter creating modern handmade ceramics from a small-batch studio in Halifax.",
  },
  // Prince Edward Island
  {
    name: "Daphne Large",
    studio: "Village Pottery",
    city: "New London",
    province: "Prince Edward Island",
    country: "CA",
    website: "https://www.villagepottery.ca",
    bio: "The longest-running pottery shop on PEI, established in 1973. Functional and decorative pieces handmade on-site using in-house glazes.",
  },
  // Newfoundland
  {
    name: "Potter by the Sea Studio",
    city: "Portugal Cove",
    province: "Newfoundland",
    country: "CA",
    website: "https://potterbytheseastudio.com",
    bio: "Functional ceramics with playful, nostalgic designs made in Portugal Cove, Newfoundland.",
  },
  // Saskatchewan
  {
    name: "Vicki Gauthier",
    studio: "Penny Lane Pottery",
    city: "Prince Albert",
    province: "Saskatchewan",
    country: "CA",
    website: "https://www.pennylanepottery.com",
    bio: "Handmade mugs and functional pottery made with a passion for the stories that handmade objects tell.",
  },
  {
    name: "Paula Cooley",
    city: "Saskatoon",
    province: "Saskatchewan",
    country: "CA",
    website: "https://paulacooley.com",
    bio: "Full-time ceramics artist with an active studio practice since 1999, creating both functional pottery and sculptural ceramics.",
  },
  // Tennessee
  {
    name: "Bryan Blankenship",
    city: "Memphis",
    province: "Tennessee",
    country: "US",
    website: "https://www.bryanblankenship.com",
  },
  {
    name: "April Dupuis",
    studio: "The Potter's Hands Studio",
    city: "Memphis",
    province: "Tennessee",
    country: "US",
    website: "https://www.thepottershandsstudio.com",
  },
  {
    name: "Angela Kilpatrick",
    studio: "Willowberry Studio",
    city: "Memphis",
    province: "Tennessee",
    country: "US",
    website: "https://www.willowberrystudio.com",
  },
  {
    name: "Amanda Kohr",
    studio: "Combustion Ceramics",
    city: "Memphis",
    province: "Tennessee",
    country: "US",
    website: "https://combustionceramics.com",
  },
  // Montana
  {
    name: "Carl Sheehan",
    studio: "Fire Hole Pottery",
    city: "Bozeman",
    province: "Montana",
    country: "US",
    website: "https://fireholepottery.com",
    bio: "Resident potter at Yellowstone National Park for over 40 years. Handcrafted stoneware and porcelain inspired by Yellowstone and the Rocky Mountains.",
  },
  // New Mexico
  {
    name: "Theo Helmstadter",
    studio: "Green River Pottery",
    city: "Santa Fe",
    province: "New Mexico",
    country: "US",
    website: "https://www.greenriverpottery.com",
    bio: "Studio potter since 1998 in Santa Fe. Stoneware with an emphasis on everyday use — plates, bowls, teapots, platters, and vases.",
  },
  // Tennessee
  {
    name: "Melissa Bridgman",
    studio: "Bridgman Pottery",
    city: "Memphis",
    province: "Tennessee",
    country: "US",
    website: "https://www.bridgmanpottery.com",
    bio: "Handmade porcelain and stoneware pottery for tables, kitchens, and gardens, made in Midtown Memphis.",
  },
  {
    name: "Agnes Stark",
    studio: "Agnes Stark Pottery",
    city: "Memphis",
    province: "Tennessee",
    country: "US",
    website: "https://agnestarkpottery.com",
    bio: "Functional stoneware and decorative porcelain widely recognized for its appealing originality.",
  },
  // Vermont
  {
    name: "James Zilian",
    studio: "Farmhouse Pottery",
    city: "Woodstock",
    province: "Vermont",
    country: "US",
    website: "https://www.farmhousepottery.com",
    bio: "Founded in 2012 in Woodstock, Vermont. Every piece begins with skilled hands and a love for the craft.",
  },
  // Wisconsin
  {
    name: "Andrew Linderman",
    studio: "Andrew Linderman Pottery",
    city: "Arena",
    province: "Wisconsin",
    country: "US",
    website: "https://www.lindermanpottery.com",
    bio: "Handcrafted functional ceramics inspired by the natural world, exploring glaze chemistry and atmospheric firing. Studio west of Madison.",
  },
  {
    name: "Ashley Pfannenstiel",
    studio: "Wilson Creek Pottery",
    city: "Spring Green",
    province: "Wisconsin",
    country: "US",
    website: "https://wilsoncreekpottery.com",
    bio: "Functional ceramics including mugs and bowls designed to fit into everyday life, made in Spring Green.",
  },
  // Wyoming
  {
    name: "Dustin Stephenson",
    studio: "Stephenson Ceramics",
    city: "Ten Sleep",
    province: "Wyoming",
    country: "US",
    website: "https://www.stephensonceramics.net",
    bio: "One-of-a-kind handmade pottery with western flair from a studio at the base of the Big Horn mountains in Ten Sleep, Wyoming.",
  },
  // Oregon
  {
    name: "Sarah Wolf",
    studio: "Wolf Ceramics",
    city: "Hood River",
    province: "Oregon",
    country: "US",
    website: "https://wolfceramics.com",
    bio: "Woman-led handmade pottery studio making contemporary ceramic dinnerware from a production studio in Hood River, Oregon.",
  },
  {
    name: "Sarah Van Raden",
    studio: "Notary Ceramics",
    city: "Portland",
    province: "Oregon",
    country: "US",
    website: "https://notaryceramics.com",
    bio: "Handcrafted wheel-thrown and altered ceramics made in Portland, Oregon — functional pieces with a quiet, considered aesthetic.",
  },
  {
    name: "Carisa Miller",
    studio: "LULA Pottery",
    city: "Portland",
    province: "Oregon",
    country: "US",
    website: "https://lulapottery.com",
    bio: "Handmade functional pottery made in Portland with a focus on everyday pieces that bring joy to the table.",
  },
  // Colorado
  {
    name: "Curt Hammerly",
    studio: "Hammerly Ceramics",
    city: "Denver",
    province: "Colorado",
    country: "US",
    website: "https://www.hammerlyceramics.com",
    bio: "Designs and crafts one-of-a-kind porcelain mugs and ceramic art from a studio outside Denver.",
  },
  // New York
  {
    name: "Jessica Weinberg",
    studio: "Firehouse Pottery Co.",
    city: "Hudson Valley",
    province: "New York",
    country: "US",
    website: "https://www.firehousepotteryco.com",
    bio: "Handmade ceramics and tableware in regional stonewares and terra cotta, continuing the tradition of Americana makers in the Hudson Valley.",
  },
  // North Carolina
  {
    name: "Sam Dougherty",
    studio: "Sam Dougherty Pottery",
    city: "Stokes County",
    province: "North Carolina",
    country: "US",
    website: "https://samdoughertypottery.com",
    bio: "Full-time studio potter near Hanging Rock State Park, making functional handcrafted pottery and dinnerware with a wood-fired kiln.",
  },
  // Georgia
  {
    name: "Rebecca Wood",
    studio: "R.Wood Studio",
    city: "Athens",
    province: "Georgia",
    country: "US",
    website: "https://rwoodstudio.com",
    bio: "Handmade dinnerware and serving pieces crafted since 1991. One of the largest pottery studios in America, known for colourful, durable red earthenware.",
  },
  // Massachusetts
  {
    name: "Lucy Fagella",
    city: "Greenfield",
    province: "Massachusetts",
    country: "US",
    website: "https://www.lucyfagella.com",
    bio: "Handmade functional pottery for the home and heart, made one at a time in Greenfield, Massachusetts.",
  },
  {
    name: "Kristen Kieffer",
    studio: "Kieffer Ceramics",
    city: "Templeton",
    province: "Massachusetts",
    country: "US",
    website: "https://kiefferceramics.com",
    bio: "Functional pottery handmade in central Massachusetts. Known for intricate surface decoration and refined technique.",
  },
  {
    name: "Jill Rosenwald",
    city: "Boston",
    province: "Massachusetts",
    country: "US",
    website: "https://www.jillrosenwald.com",
    bio: "Colorful handmade ceramic vases, lamps, and trays made in Boston.",
  },
  // Minnesota
  {
    name: "Joel Cherrico",
    studio: "Cherrico Pottery",
    city: "St. Joseph",
    province: "Minnesota",
    country: "US",
    website: "https://cherricopottery.com",
    bio: "Beautiful handmade pottery made in St. Joseph, Minnesota.",
  },
  // Ohio
  {
    name: "Gina DeSantis",
    studio: "Gina DeSantis Ceramics",
    city: "Lakewood",
    province: "Ohio",
    country: "US",
    website: "https://www.ginadesantisceramics.com",
    bio: "Rustic yet refined handmade ceramic tableware made in Lakewood, Ohio. Featured in Food & Wine and sold through Anthropologie and Nordstrom.",
  },
  {
    name: "Tim Frederich",
    studio: "Frederich Pottery",
    city: "Dublin",
    province: "Ohio",
    country: "US",
    website: "https://frederichpottery.com",
    bio: "Over four decades of experience in hand-thrown stoneware and sculpture, based in Dublin, Ohio.",
  },
  // Arizona
  {
    name: "Mark Arnegard",
    studio: "Arne Ceramics",
    city: "Flagstaff",
    province: "Arizona",
    country: "US",
    website: "https://www.azhandmade.com/mark-arne-arnegard.html",
    bio: "Handmade ceramics studio on historic Route 66 in Flagstaff, Arizona.",
  },
  // Illinois
  {
    name: "Danielle Chutinthranond",
    studio: "Monsoon Pottery",
    city: "Chicago",
    province: "Illinois",
    country: "US",
    website: "https://monsoonpottery.com",
    bio: "Porcelain pottery inspired by Asian art history and food culture, made in Chicago's West Town neighbourhood. Hand-carved inlay work combining blue & white porcelain aesthetics.",
  },
  // Maine
  {
    name: "Amy Clark",
    studio: "Ocean Fire Pottery",
    city: "York",
    province: "Maine",
    country: "US",
    website: "https://oceanfirepottery.com",
    bio: "Wheel-thrown stoneware and wood-fired pottery from a studio and gallery in York Village, Maine. Open since 2009.",
  },
  // Pennsylvania
  {
    name: "Francis DeFabo",
    studio: "fdp studio+shop",
    city: "Pleasant Unity",
    province: "Pennsylvania",
    country: "US",
    website: "https://www.fdpstudioshop.com",
    bio: "Small-batch ceramics made in a restored historic building forty minutes east of Pittsburgh.",
  },
  // Texas
  {
    name: "Stephen Salter",
    studio: "Stephen Salter Pottery",
    city: "Dallas",
    province: "Texas",
    country: "US",
    website: "https://stephensalterpottery.com",
    bio: "Brings meaningful handcrafted ceramics to the Oak Cliff community in Dallas. Started in 2018 after an apprenticeship at The Barn Pottery.",
  },
  // Florida
  {
    name: "Osa Atoe",
    studio: "Pottery by Osa",
    city: "Tampa",
    province: "Florida",
    country: "US",
    website: "https://potterybyosa.com",
    bio: "Handmade functional and decorative ceramics made in Tampa, Florida — earthy, expressive pieces with bold surface texture and personal meaning.",
  },
  {
    name: "Melissa Bridgman",
    studio: "Bridgman Pottery",
    city: "Memphis",
    province: "Tennessee",
    country: "US",
    website: "https://www.bridgmanpottery.com",
    bio: "A Midtown Memphis studio producing fine handmade porcelain and stoneware for the table, kitchen, and garden.",
  },
  // Washington
  {
    name: "Stephanie Cao",
    studio: "Studio Cao",
    city: "Seattle",
    province: "Washington",
    country: "US",
    website: "https://www.studio-cao.com",
    bio: "Wheel-thrown and hand-built functional ceramics inspired by PNW landscapes and mid-century modern design, made from a Wallingford studio in Seattle.",
  },
  // Michigan
  {
    name: "Sarah Gelsanliter & Thomas Gelsanliter",
    studio: "One Acre Ceramics",
    city: "Milan",
    province: "Michigan",
    country: "US",
    website: "https://www.oneacreceramics.com",
    bio: "A husband-and-wife studio known for luminous glazes and hand-carved tile designs combined with wheel-thrown art pottery vessels.",
  },
  {
    name: "Benjamin Maier",
    studio: "Maier Ceramics",
    city: "Traverse City",
    province: "Michigan",
    country: "US",
    website: "https://www.maierceramics.com",
    bio: "A production studio on 45 acres creating elevated everyday stoneware, best known for their signature Dimple Cup.",
  },
  {
    name: "Peter Johnson",
    studio: "Terrestrial Forming",
    city: "Whitehall",
    province: "Michigan",
    country: "US",
    website: "https://www.terrestrialforming.com",
    bio: "A master potter with 50+ years of experience creating timeless functional vessels from his West Michigan studio.",
  },
  // Virginia
  {
    name: "Mallorie Morrison",
    studio: "Jars of Dust",
    city: "Virginia Beach",
    province: "Virginia",
    country: "US",
    website: "https://jarsofdust.com",
    bio: "Durable high-fired wheel-thrown and hand-built tableware in clean, solid-colour glazes designed for everyday use.",
  },
  // Tennessee
  {
    name: "Morgan Hendrix",
    studio: "Handmade Studio TN",
    city: "Nashville",
    province: "Tennessee",
    country: "US",
    website: "https://www.handmadestudiotn.com",
    bio: "A Germantown neighbourhood studio dedicated since 2012 to organic, minimalist handcrafted ceramics and dinnerware for the table.",
  },
  // Missouri
  {
    name: "Rebecca A. Koop",
    studio: "Back Door Pottery",
    city: "Kansas City",
    province: "Missouri",
    country: "US",
    website: "https://backdoorpottery.com",
    bio: "A working studio operating since 1979, specialising in original stoneware, porcelain, custom tiles, mosaic, and Egyptian paste ceramics.",
  },
  // New Mexico
  {
    name: "Theo Helmstadter",
    studio: "Green River Pottery",
    city: "Santa Fe",
    province: "New Mexico",
    country: "US",
    website: "https://www.greenriverpottery.com",
    bio: "A full-time studio potter since 1998 making high-fired reduction stoneware — plates, bowls, teapots, and platters — from local Abiquiu clay.",
  },
  {
    name: "Sage Valley Pottery",
    city: "Corrales",
    province: "New Mexico",
    country: "US",
    website: "https://sagevalleypottery.com",
    bio: "Established 1995, hand-throwing small-batch stoneware heirlooms using traditional techniques with no moulds or machines.",
  },
  // Vermont
  {
    name: "Ulrike Tessmer",
    studio: "Waitsfield Pottery",
    city: "Waitsfield",
    province: "Vermont",
    country: "US",
    website: "https://waitsfieldpottery.com",
    bio: "Hand-thrown stoneware fired at high temperature in historic Waitsfield Village, decorated with richly textured engobes and glazes.",
  },
  {
    name: "Amelia Wrede Davis",
    city: "Vermont",
    province: "Vermont",
    country: "US",
    website: "https://www.ameliawrededavis.com",
    bio: "An 18-year practice creating utilitarian wheel-thrown tableware rooted in slow food, folk art traditions, and the natural world.",
  },
  {
    name: "Laura Zindel",
    studio: "Laura Zindel Design",
    city: "Brattleboro",
    province: "Vermont",
    country: "US",
    website: "https://www.laurazindel.com",
    bio: "Handmade ceramic dinnerware and homewares adorned with detailed naturalist illustrations of animals and botanicals, produced since 1997.",
  },
  {
    name: "Stephen Procter",
    studio: "Stephen Procter Studios",
    city: "Brattleboro",
    province: "Vermont",
    country: "US",
    website: "https://www.stephenprocter.com",
    bio: "Specialises in large-scale monumental ceramic vessels and sculptural garden pots, with a focus on form, proportion, and spatial presence.",
  },
  // Connecticut
  {
    name: "Heather Purring",
    studio: "Purring Pottery",
    city: "Colchester",
    province: "Connecticut",
    country: "US",
    website: "https://www.purringpottery.com",
    bio: "Wheel-thrown pottery with hand-built elements made with non-toxic, food-safe glazes, alongside adult and children's classes from her Colchester studio.",
  },
  // New Hampshire
  {
    name: "Brian O'Hare",
    studio: "Ripple Pottery",
    city: "Rumney",
    province: "New Hampshire",
    country: "US",
    website: "https://www.ripplepottery.com",
    bio: "Nearly three decades of experience producing high-fired stoneware and porcelain that blends practical forms with subtle artistic detail.",
  },
  // Delaware
  {
    name: "Audrey Mason",
    studio: "Pottery Mason",
    city: "Rehoboth Beach",
    province: "Delaware",
    country: "US",
    website: "https://www.potterymason.com",
    bio: "Coastal-inspired handcrafted ceramics sold from a studio and shop in downtown Rehoboth Beach.",
  },
  // Hawaii
  {
    name: "Dean McRaine",
    studio: "LightWave Pottery",
    city: "Kapa'a",
    province: "Hawaii",
    country: "US",
    website: "https://www.lightwavepottery.com",
    bio: "A collaborative Kauai studio producing vibrant, food-safe functional ware blending wheel throwing, hand building, and ceremonial ceramic traditions.",
  },
  // Montana
  {
    name: "Katie Redfield",
    studio: "Open Sky Arts Montana",
    city: "Butte",
    province: "Montana",
    country: "US",
    website: "https://www.openskyartsmontana.com",
    bio: "Functional stoneware with hand-carved Montana landscape imagery — each piece carries the story of the state's heritage.",
  },
  // Wyoming
  {
    name: "Tana Libolt & West Magoon",
    studio: "Muddy Mountain Pottery",
    city: "Centennial",
    province: "Wyoming",
    country: "US",
    website: "https://www.muddymountainpottery.com",
    bio: "High-fired stoneware and Raku sculptures from a Wyoming mountain studio, including practical functional ware and one-of-a-kind Raku pieces.",
  },
  // England
  {
    name: "Edmund de Waal",
    city: "London",
    province: "England",
    country: "EU",
    website: "https://www.edmunddewaal.com",
    bio: "Internationally renowned potter and author of The Hare with Amber Eyes, creating luminous porcelain installations exploring themes of memory and place, exhibited at major institutions worldwide.",
  },
  {
    name: "Florian Gadsby",
    city: "London",
    province: "England",
    country: "EU",
    website: "https://www.floriangadsby.com",
    bio: "A leading young British studio potter creating refined functional and decorative wheel-thrown vessels in stoneware glazes, known internationally through his popular YouTube channel and his 2023 book By My Hands.",
  },
  {
    name: "Lisa Hammond",
    city: "London",
    province: "England",
    country: "EU",
    website: "https://www.lisahammond-pottery.co.uk",
    bio: "A celebrated soda-firing potter working from her Maze Hill Pottery — established in 1994 inside a Victorian railway ticket office — creating loose, gestural vessels fired in her atmospheric soda kiln.",
  },
  {
    name: "Jim Malone",
    city: "Cumbria",
    province: "England",
    country: "EU",
    website: "http://www.jimmalonepottery.co.uk",
    bio: "One of Britain's most respected studio potters, drawing from medieval English and Korean traditions to make wood-fired jugs, bottles, and Hakeme-decorated pieces from his remote Cumbrian studio for over forty years.",
  },
  {
    name: "Simon Olley",
    city: "Kent",
    province: "England",
    country: "EU",
    website: "https://www.olleypottery.co.uk",
    bio: "A Selected Member of the Craft Potters Association whose illustrated sgraffito ceramics honour the bond between humans and their dogs, hand-thrown in earthenware and stoneware with intricate scratched decoration.",
  },
  {
    name: "Catherine West & Matt West",
    studio: "Pottery West",
    city: "London",
    province: "England",
    country: "EU",
    website: "https://www.potterywest.co.uk",
    bio: "A London studio producing hand-thrown stoneware with bold, graphic glazes — functional pieces made with a strong graphic sensibility and a love of colour.",
  },
  {
    name: "Alan Parris & Billy Byles",
    studio: "Aylesford Pottery",
    city: "Aylesford",
    province: "England",
    country: "EU",
    website: "https://www.aylesfordpottery.co.uk",
    bio: "A working pottery in the heart of Kent producing functional wood-fired stoneware, with a long tradition of craft rooted in the English countryside.",
  },
  // Scotland
  {
    name: "Lotte Glob",
    city: "Sutherland",
    province: "Scotland",
    country: "EU",
    website: "https://www.lotteglob.co.uk",
    bio: "A Danish-born ceramic artist who has lived and worked on Scotland's remote northwest coast for over 50 years, creating sculptural pieces deeply connected to the Highland landscape, geology, and weather.",
  },
  {
    name: "Hannah McAndrew",
    studio: "Fitch & McAndrew",
    city: "Castle Douglas",
    province: "Scotland",
    country: "EU",
    website: "https://fitchandmcandrew.co.uk",
    bio: "An internationally recognised slipware potter working with partner Douglas Fitch in a rural studio with a wood-fired kiln, producing hand-thrown earthenware decorated with traditional slip-trailing and sgraffito.",
  },
  {
    name: "Katie Rose Johnston",
    studio: "Studio Manifesto",
    city: "Edinburgh",
    province: "Scotland",
    country: "EU",
    website: "https://studiomanifesto.co.uk",
    bio: "An Edinburgh-based ceramicist creating delicate hand-built porcelain pieces inspired by the natural world — botanical forms, shells, and textures translated into quiet, refined objects.",
  },
  // Wales
  {
    name: "Richard Prentice",
    studio: "Blackbird Ceramics",
    city: "Pembrokeshire",
    province: "Wales",
    country: "EU",
    website: "https://www.blackbirdceramics.co.uk",
    bio: "A studio potter working in the Pembrokeshire Coast National Park, making hand-thrown functional stoneware with an earthy, landscape-influenced palette.",
  },
  {
    name: "Tom Loveday & Myfanwy James",
    studio: "Glosters",
    city: "Monmouthshire",
    province: "Wales",
    country: "EU",
    website: "https://www.glosters.co.uk",
    bio: "A small Welsh studio producing hand-thrown domestic pottery — tactile, unpretentious pieces for everyday use, made with local sensibility and a quiet attention to material.",
  },
  // Ireland
  {
    name: "Elaine Fallon",
    studio: "Brookwood Pottery",
    city: "Dublin",
    province: "Ireland",
    country: "EU",
    website: "https://brookwoodpottery.com",
    bio: "Established in 2012, Brookwood Pottery is a design studio and teaching space in Dublin making handcrafted functional ceramics and running classes for the local community.",
  },
  {
    name: "Charlie Mahon",
    city: "Cork",
    province: "Ireland",
    country: "EU",
    website: "https://charliemahonceramicspottery.com",
    bio: "An award-winning ceramic artist hand-painting and wheel-throwing vivid Irish-themed earthenware from his studio in Cork's English Market, with all pieces fired in his own kiln.",
  },
  {
    name: "Amanda Murphy",
    city: "Co. Waterford",
    province: "Ireland",
    country: "EU",
    website: "https://amandamurphyceramics.com",
    bio: "A coastal Co. Waterford potter whose hand-built and wheel-thrown pieces are inspired by the Irish landscape — vases, bowls, and platters textured with the colours of sea, sand, mountains, and rock.",
  },
  // France
  {
    name: "Maureen Stengel-Guillot",
    studio: "MSG Céramique",
    city: "Vallauris",
    province: "France",
    country: "EU",
    website: "https://www.msg-ceramique.com",
    bio: "Working in Vallauris — the pottery town made famous by Picasso — Maureen hand-builds all her pieces combining Limoges porcelain traditions with contemporary Provençal techniques.",
  },
  // Germany
  {
    name: "Elizaveta Barsega",
    studio: "Barsega Studio",
    city: "Berlin",
    province: "Germany",
    country: "EU",
    website: "https://brsg-keramik.com",
    bio: "A research-driven ceramics practice devoted to locally sourced natural minerals and wood ash glazes, making mindfully crafted vessels from wild-harvested materials with workshops in sustainable techniques.",
  },
  {
    name: "Marilyne Blais",
    city: "Berlin",
    province: "Germany",
    country: "EU",
    website: "https://www.marilyneblais.com",
    bio: "A French-Canadian ceramic artist who founded her studio in Berlin in 2018, creating bold, colourful handmade vessels with vibrant airbrushed gradient glazes, alongside teaching wheel-throwing classes.",
  },
  // Netherlands
  {
    name: "Marjoke de Heer",
    city: "Amsterdam",
    province: "Netherlands",
    country: "EU",
    website: "https://marjokedeheer.com",
    bio: "A studio potter and gallery-holder working from her Amsterdam riverside studio since 1994, creating one-of-a-kind stoneware, porcelain, and wild clay vessels using ancient glazes and contemporary design.",
  },
  {
    name: "Lonny van Ryswyck",
    studio: "AtelierNL",
    city: "Eindhoven",
    province: "Netherlands",
    country: "EU",
    website: "https://www.ateliernl.com",
    bio: "A design-led ceramics studio that digs local Dutch clays to make place-specific ceramics and glass, translating the geology and history of each location into objects. Dezeen Designer of the Year.",
  },
  {
    name: "Camille Verbunt",
    studio: "Made in Mokum",
    city: "Amsterdam",
    province: "Netherlands",
    country: "EU",
    website: "https://www.madeinmokum.com",
    bio: "An Amsterdam-based potter who celebrates the character of handmade objects, throwing wonky stoneware bowls, vases, and pots with homebrew glazes — embracing imperfection as part of the work's personality.",
  },
  // Portugal
  {
    name: "Ian Fitzpatrick",
    studio: "Olaria Pequena",
    city: "Porches",
    province: "Portugal",
    country: "EU",
    website: "https://www.olariapequena.com",
    bio: "A Scottish-born potter who came to Portugal in 1981, this intimate Algarve studio produces handcrafted pottery and tiles blending traditional Portuguese craft with contemporary sensibility.",
  },
  {
    name: "Gaëlle Van Branteghem",
    studio: "Gaëlle Ceramica",
    city: "Ericeira",
    province: "Portugal",
    country: "EU",
    website: "https://www.gaelleceramica.com",
    bio: "A Belgian-born ceramist who moved to Ericeira in 2017, creating wheel-thrown stoneware tableware and interior pieces inspired by the wild coastal landscapes near Lisbon.",
  },
  // Denmark
  {
    name: "Anne Black",
    city: "Copenhagen",
    province: "Denmark",
    country: "EU",
    website: "https://www.anneblack.com",
    bio: "A Danish ceramicist and designer who has worked exclusively in porcelain since graduating from the Danish Design School in 1996, creating handmade contemporary ceramics, jewellery, and homewares.",
  },
  {
    name: "Eric Landon",
    studio: "TORTUS Copenhagen",
    city: "Copenhagen",
    province: "Denmark",
    country: "EU",
    website: "https://tortus.dk",
    bio: "An American-born master potter based in Copenhagen who has taught over 10,000 students in 30+ countries, creating hand-thrown stoneware that blends timeless craftsmanship with a clean Scandinavian aesthetic.",
  },
  // Sweden
  {
    name: "Evelina Hedberg",
    studio: "Imse Studios",
    city: "Stockholm",
    province: "Sweden",
    country: "EU",
    website: "https://imsestudios.com",
    bio: "A Stockholm ceramicist inspired by the Swedish archipelago and Gotland, creating handcrafted cups, bowls, vases, and plates from her studio on Frejgatan.",
  },
  {
    name: "Eva Gassne-Jeckelmann",
    studio: "Swedenland Ceramics",
    city: "Limhamn",
    province: "Sweden",
    country: "EU",
    website: "https://swedenland.se",
    bio: "An experimental studio in southern Sweden creating bespoke and limited-edition ceramic pieces that blur the line between functional object and expressive art, with humour and colour at the heart of the practice.",
  },
  // Norway
  {
    name: "Elisa Helland-Hansen",
    city: "Seimsfoss",
    province: "Norway",
    country: "EU",
    website: "https://www.elisahh.no",
    bio: "A full-time studio potter trained at Bergen National College for Arts and Design, making quietly considered cups, mugs, teapots, and bowls from her studio overlooking the Hardangerfjord.",
  },
  {
    name: "Irene Nordli",
    city: "Oslo",
    province: "Norway",
    country: "EU",
    website: "https://www.irenenordli.no",
    bio: "A leading Norwegian ceramic sculptor and professor emeritus at the Oslo National Academy of the Arts, whose figurative porcelain works have been exhibited across Europe and beyond.",
  },
  {
    name: "Tonje & Constance",
    studio: "Odd Standard",
    city: "Stavanger",
    province: "Norway",
    country: "EU",
    website: "http://www.oddstandard.no",
    bio: "A design duo creating handcrafted restaurant tableware and homeware from a Stavanger ceramics microfactory, with a focus on considered Scandinavian aesthetics and collaborations with the food industry.",
  },
  // Finland
  {
    name: "Eva Spoof",
    studio: "Udumbara Studio",
    city: "Helsinki",
    province: "Finland",
    country: "EU",
    website: "https://udumbara.fi",
    bio: "An earth-friendly ceramics studio founded in 1994 in Helsinki's Kallio district, creating handmade sculptural planters, lamps, and flowerpots from locally sourced wild clay.",
  },
  {
    name: "Janine Gerber Moser",
    studio: "Orava Studio",
    city: "Finnish countryside",
    province: "Finland",
    country: "EU",
    website: "https://oravastudio.com",
    bio: "A Swiss-rooted artist living in rural Finland who shapes hand-formed ceramic pieces inspired by the quiet rhythms and light of Nordic nature.",
  },
  {
    name: "Pekka Paikkari",
    city: "Helsinki",
    province: "Finland",
    country: "EU",
    website: "https://www.pekkapaikkari.com",
    bio: "A Helsinki-based ceramic sculptor internationally recognised for his large-scale stoneware wall reliefs and public installations, with work held in the British Museum and the V&A.",
  },
  // Italy
  {
    name: "Arianna De Luca",
    city: "Rome",
    province: "Italy",
    country: "EU",
    website: "https://ariannadeluca.it",
    bio: "A Rome-based designer and ceramicist with an MA from Central Saint Martins, creating bold collectible ceramic objects — vases, lamps, and vessels — blending Mediterranean heritage with contemporary colour and form.",
  },
  {
    name: "Paola Paronetto",
    city: "Porcia",
    province: "Italy",
    country: "EU",
    website: "https://www.paolaparonetto.com",
    bio: "A pioneering ceramicist whose signature paper clay Cartocci collection produces objects that are solid yet astonishingly thin and light, with solo exhibitions from New York to London.",
  },
  {
    name: "Terry Davies",
    studio: "Pino Scarpeto Ceramics",
    city: "Certaldo",
    province: "Italy",
    country: "EU",
    website: "https://terrydavies.it",
    bio: "A British-born potter who settled in Tuscany in the late 1990s, creating reduction-fired stoneware and porcelain vessels in the Leach tradition — including tea bowls and ikebana vases with surfaces shaped by deliberate cracking and heat.",
  },
  // Spain
  {
    name: "Jordina Ferrando",
    studio: "JorCeramics",
    city: "Banyoles",
    province: "Spain",
    country: "EU",
    website: "https://jorceramics.com",
    bio: "Working from her grandfather's former shop in Banyoles, Jordina hand-builds voluptuous sculptural and functional pieces deeply rooted in Mediterranean sensibility, represented by galleries in Madrid, Barcelona, and Girona.",
  },
  {
    name: "Wendy Gingell",
    studio: "Taller Gingell",
    city: "Barcelona",
    province: "Spain",
    country: "EU",
    website: "https://tallergingell.com",
    bio: "A studio ceramicist making small-batch heirloom ceramics — cups, plates, platters, candle holders, and jewellery — from a Barcelona workshop, blending traditional craft with contemporary design.",
  },
  // Belgium
  {
    name: "Veerle Van Overloop",
    studio: "Fou de Feu",
    city: "Vrasene",
    province: "Belgium",
    country: "EU",
    website: "https://www.foudefeu.com",
    bio: "A Belgian ceramic designer whose studio makes refined handcrafted tableware and decorative objects — candleholders, vases, and coffee sets — influenced by architecture, photography, and food culture.",
  },
  {
    name: "Ann Reheul-Van Beersel",
    studio: "Artisann",
    city: "Knokke",
    province: "Belgium",
    country: "EU",
    website: "https://www.artisann.be",
    bio: "A ceramicist with a restaurant background creating handcrafted contemporary tableware, vases, and decorative porcelain from a studio-gallery at the Knokke lighthouse, certified Handmade in Belgium.",
  },
  {
    name: "Studio Pieter Stockmans",
    city: "Genk",
    province: "Belgium",
    country: "EU",
    website: "https://studiostockmans.com",
    bio: "A celebrated Belgian hard-paste porcelain studio at the C-mine arts complex in Genk, creating precisely formed handcrafted collections for chefs and collectors — a Belgian Royal Warrant Holder since 2024.",
  },
  // New South Wales
  {
    name: "Daniel Lafferty",
    studio: "Bandicoot Pottery",
    city: "Cobargo",
    province: "New South Wales",
    country: "AU",
    website: "https://www.bandicootpottery.com.au",
    bio: "A studio operating since 1990 in the Cobargo Valley, specialising in functional, decorative one-off wood-fired pieces and offering ceramics classes in a community-focused creative environment.",
  },
  // Victoria
  {
    name: "Jennifer Hodges",
    studio: "Woolshed Ceramics",
    city: "Wooragee",
    province: "Victoria",
    country: "AU",
    website: "https://woolshedceramics.com.au",
    bio: "A ceramic artist working from a converted 1940s shearing shed in Victoria's High Country, creating functional handmade wares in organic shapes with earthy glazes reflecting the Australian landscape.",
  },
  {
    name: "Sophie Moran",
    city: "Melbourne",
    province: "Victoria",
    country: "AU",
    website: "https://sophiemoran.studio",
    bio: "A Melbourne ceramic artist making wheel-thrown functional and decorative stoneware — soft, considered pieces inspired by landscape and light.",
  },
  {
    name: "Throughgood Pottery",
    city: "Ballarat",
    province: "Victoria",
    country: "AU",
    website: "https://throughgoodpottery.com.au",
    bio: "A Ballarat studio making handcrafted functional pottery — mugs, bowls, and vases with an honest, tactile quality rooted in the central Victorian landscape.",
  },
  // South Australia
  {
    name: "Alison Arnold",
    studio: "Red Bird Studio",
    city: "Hawthorndene",
    province: "South Australia",
    country: "AU",
    website: "https://redbirdstudioart.com",
    bio: "A full-time studio potter and teacher with over 30 years of experience, trained at Adelaide's JamFactory, making sculptural and functional pottery inspired by Australian flora and fauna.",
  },
  // Western Australia
  {
    name: "Anika Kalotay",
    studio: "Kura Studio",
    city: "Perth",
    province: "Western Australia",
    country: "AU",
    website: "https://kurastudio.com",
    bio: "A ceramics and creative practice making small-batch handmade ceramics — palm-fitting vases, topography-inspired jewellery trays, and paired everyday objects — focused on thoughtful, responsive design.",
  },
  {
    name: "Danica Wichtemann",
    studio: "Rediscover Ceramics",
    city: "Perth",
    province: "Western Australia",
    country: "AU",
    website: "https://www.rediscovering.com.au",
    bio: "A ceramic artist who carves Southern Ice Porcelain with detailed illustrations of native Australian flowers and birds, inlaying glazes for colour and texture. Work stocked at Fremantle Arts Centre.",
  },
  // Queensland
  {
    name: "Rowley Drysdale",
    studio: "Quixotica Art Space",
    city: "Cooroy",
    province: "Queensland",
    country: "AU",
    website: "https://www.rowleydrysdale.com.au",
    bio: "One of Australia's foremost wood-firing potters, born in western Queensland, drawing on the Australian bush as central inspiration and internationally connected with potters in South Korea, Japan, and Finland.",
  },
  {
    name: "Melanie Hardy",
    city: "Brisbane",
    province: "Queensland",
    country: "AU",
    website: "https://www.melaniehardy.com.au",
    bio: "A Brisbane-based ceramic artist creating hand-built sculptural and functional work — layered surfaces and organic forms that speak to the textures of the natural world.",
  },
  // Tasmania
  {
    name: "Christie Lange",
    city: "Bay of Fires",
    province: "Tasmania",
    country: "AU",
    website: "https://www.christielange.com.au",
    bio: "A Tasmanian ceramicist whose hand-built porcelain and stoneware sculptures investigate regeneration and ecological cycles through close study of Tasmania's terrestrial and marine environments.",
  },
  {
    name: "Ian Clare",
    studio: "Ian Clare Studio Potter",
    city: "Cygnet",
    province: "Tasmania",
    country: "AU",
    website: "https://www.ianclarestudiopotter.com",
    bio: "A master potter in the Huon Valley trained under Japanese master Shigeo Shiga, producing high-quality functional domestic ware strongly influenced by Japanese ceramic traditions.",
  },
  {
    name: "Alice Holder & Isaac Patmore",
    studio: "Small Fires Studio",
    city: "Hobart",
    province: "Tasmania",
    country: "AU",
    website: "https://smallfiresstudio.com.au",
    bio: "A duo creating handmade functional ceramics for the table and kitchen from their Mornington studio, with custom glazes, commissions, and a regular presence at Salamanca Markets.",
  },
  // ACT
  {
    name: "Anita McIntyre",
    city: "Canberra",
    province: "ACT",
    country: "AU",
    website: "https://anitamcintyre.com.au",
    bio: "A senior figure in Australian ceramics with over 50 years of practice and a Visiting Fellowship at ANU, creating platters and forms expressing a profound engagement with the Australian landscape and desert country.",
  },
  {
    name: "Amy Williams",
    studio: "Deep Blue Ceramics",
    city: "Weston",
    province: "ACT",
    country: "AU",
    website: "https://deepblueceramics.com",
    bio: "A women- and veteran-owned studio in a solar-powered shipping container workshop, making handmade functional ceramic homewares and custom commissions, net-zero certified.",
  },
  // New Zealand
  {
    name: "Nicola Shuttleworth",
    city: "Wellington",
    province: "New Zealand",
    country: "AU",
    website: "https://www.nicolashuttleworth.co.nz",
    bio: "A Wellington potter with twenty years of practice making functional stoneware — stacks, groups, and individual pieces — using wild clay blends and self-mixed glazes in warm, natural tones.",
  },
  {
    name: "Richard Beauchamp",
    city: "Christchurch",
    province: "New Zealand",
    country: "AU",
    website: "https://richardbeauchamp.studio",
    bio: "A Christchurch-based ceramicist whose tactile wheel-thrown and hand-built mugs, plates, bowls, and vases are shaped by a deep background in coffee culture and hospitality.",
  },
  {
    name: "Rachel Carter",
    city: "Titirangi",
    province: "New Zealand",
    country: "AU",
    website: "https://www.rachelcarterceramics.com",
    bio: "Working daily from her Titirangi studio, Rachel throws, turns, glazes, and fires stoneware with well-balanced forms and muted tones, accepting bespoke commissions from chefs, hoteliers, and architects.",
  },
  {
    name: "Alex",
    studio: "Mystery Creek Ceramics",
    city: "Waikato",
    province: "New Zealand",
    country: "AU",
    website: "https://mysterycreekceramics.co.nz",
    bio: "A Waikato ceramicist who specialises in nerikomi — a Japanese patterning technique — producing vibrantly striped and marbled vases, bowls, plates, and mugs.",
  },
];

export const suppliers: Supplier[] = [
  // British Columbia
  {
    name: "The Clay Warehouse",
    city: "Port Coquitlam",
    province: "British Columbia",
    country: "CA",
    website: "https://theclaywarehouse.com",
    bio: "Pottery supplies, wheels, kilns, and materials serving potters across BC.",
  },
  {
    name: "Greenbarn Potters' Supply",
    city: "Surrey",
    province: "British Columbia",
    country: "CA",
    website: "https://greenbarn.com",
    bio: "A BC institution for ceramic supplies, raw materials, kilns, and wheels — serving potters for decades.",
  },
  {
    name: "Vancouver Island Pottery Supply",
    city: "Parksville",
    province: "British Columbia",
    country: "CA",
    website: "https://vipotterysupply.com",
    bio: "Vancouver Island's go-to source for clay, glazes, tools, and equipment.",
  },
  // Alberta
  {
    name: "Plainsman Clays",
    city: "Medicine Hat",
    province: "Alberta",
    country: "CA",
    website: "https://plainsmanclays.com",
    bio: "One of Canada's leading clay manufacturers, producing Plainsman clay bodies used by potters coast to coast.",
  },
  {
    name: "Plainsman Pottery Supply",
    city: "Edmonton",
    province: "Alberta",
    country: "CA",
    website: "https://plainsmanpotterysupply.com",
    bio: "Full-service pottery supply store in Edmonton carrying Plainsman clays, Skutt kilns, Brent and Shimpo wheels.",
  },
  {
    name: "Ceramics Canada",
    city: "Lethbridge",
    province: "Alberta",
    country: "CA",
    bio: "Ceramic supplies, kiln equipment, and raw materials for Alberta potters.",
  },
  // Saskatchewan
  {
    name: "TREE Pottery Supply",
    city: "Saskatoon",
    province: "Saskatchewan",
    country: "CA",
    website: "https://treesaskatoon.com",
    bio: "Saskatoon's pottery supply store for over 37 years, stocking Plainsman clays, Skutt kilns, and Brent and Shimpo wheels.",
  },
  // Manitoba
  {
    name: "Sounding Stone",
    city: "Winnipeg",
    province: "Manitoba",
    country: "CA",
    website: "https://soundingstone.ca",
    bio: "Pottery supplies and ceramics equipment serving Manitoba and the Prairie provinces.",
  },
  // Ontario
  {
    name: "PSH / Euclid's",
    city: "Oakville",
    province: "Ontario",
    country: "CA",
    website: "https://www.psh.ca",
    bio: "One of Canada's largest pottery supply houses, carrying clay, glazes, tools, wheels, and kilns.",
  },
  {
    name: "Tucker's Pottery Supplies",
    city: "Richmond Hill",
    province: "Ontario",
    country: "CA",
    website: "https://tuckerspot.com",
    bio: "A well-stocked Ontario pottery supplier carrying a full range of clays, glazes, tools, wheels, and kilns.",
  },
  {
    name: "Amaranth Stoneware",
    city: "Kingston",
    province: "Ontario",
    country: "CA",
    website: "https://amaranthstoneware.com",
    bio: "Supplies, raw materials, and equipment for studio potters in Eastern Ontario.",
  },
  // Arizona
  {
    name: "Marjon Ceramics",
    city: "Phoenix",
    province: "Arizona",
    country: "US",
    website: "https://www.marjonceramics.com",
    bio: "Arizona's longest-running ceramics supply store, stocking clay bodies, glazes, tools, wheels, and kilns.",
  },
  // California
  {
    name: "Aardvark Clay & Supplies",
    city: "Santa Ana",
    province: "California",
    country: "US",
    website: "http://aardvarkclay.com",
    bio: "A Southern California staple for studio potters, carrying clay bodies, glazes, tools, and equipment.",
  },
  // Colorado
  {
    name: "Rocky Mountain Clay",
    city: "Denver",
    province: "Colorado",
    country: "US",
    website: "https://rockymountainclay.com",
    bio: "Ceramic supplies and clay bodies for studio potters throughout the Rocky Mountain region.",
  },
  {
    name: "Continental Clay Co.",
    city: "Minneapolis",
    province: "Minnesota",
    country: "US",
    website: "https://www.continentalclay.com",
    bio: "Full-service ceramics supplier with a wide selection of clay, glazes, tools, and kilns, serving potters across the Midwest.",
  },
  // Florida
  {
    name: "Axner Pottery Supply",
    city: "Oviedo",
    province: "Florida",
    country: "US",
    website: "https://www.axner.com",
    bio: "A comprehensive online pottery supplier based in Florida, stocking clay, glazes, tools, wheels, and kilns.",
  },
  {
    name: "Highwater Clays of Florida",
    city: "Clearwater",
    province: "Florida",
    country: "US",
    website: "https://highwaterclays.com",
    bio: "Florida outpost of Highwater Clays, carrying a broad range of clay bodies, glazes, and ceramic supplies.",
  },
  // Georgia
  {
    name: "Davens Ceramic Center",
    city: "Atlanta",
    province: "Georgia",
    country: "US",
    website: "https://www.davensceramiccenter.com",
    bio: "Atlanta's go-to ceramics supplier since 1946, stocking clay, glazes, tools, equipment, and kilns.",
  },
  // Idaho
  {
    name: "The Potter's Center",
    city: "Garden City",
    province: "Idaho",
    country: "US",
    website: "https://thepotterscenter.com",
    bio: "Idaho's pottery supply store and teaching space, offering clay, glazes, tools, and beginner-friendly classes.",
  },
  // Illinois
  {
    name: "Great Lakes Clay & Supply",
    city: "Carpentersville",
    province: "Illinois",
    country: "US",
    website: "https://www.greatclay.com",
    bio: "Midwest ceramic supplier stocking a wide range of clay bodies, glazes, tools, and kiln equipment.",
  },
  {
    name: "Ceramic Supply Chicago",
    city: "Chicago",
    province: "Illinois",
    country: "US",
    website: "https://ceramic-supply-chicago.myshopify.com",
    bio: "Chicago-based ceramics supply store carrying clay, glazes, tools, and accessories for studio potters.",
  },
  // Maryland
  {
    name: "Clayworks Supplies",
    city: "Baltimore",
    province: "Maryland",
    country: "US",
    website: "https://clayworkssupplies.com",
    bio: "Baltimore ceramics supplier serving the Mid-Atlantic region with clay, glazes, tools, and equipment.",
  },
  // Massachusetts
  {
    name: "Sheffield Pottery",
    city: "Sheffield",
    province: "Massachusetts",
    country: "US",
    website: "https://www.sheffield-pottery.com",
    bio: "New England's full-service pottery supplier, stocking clay, glazes, wheels, kilns, and tools for all skill levels.",
  },
  // Michigan
  {
    name: "Rovin Ceramics",
    city: "Ann Arbor",
    province: "Michigan",
    country: "US",
    website: "https://rovinceramics.com",
    bio: "Michigan-based ceramics supplier carrying clay bodies, glazes, oxides, and raw materials for studio potters.",
  },
  {
    name: "Runyan Pottery Supply",
    city: "Clio",
    province: "Michigan",
    country: "US",
    website: "https://www.runyanpotterysupply.com",
    bio: "Michigan pottery supplier with a wide selection of clays, glazes, tools, and kiln equipment.",
  },
  // Minnesota
  {
    name: "Minnesota Clay Co.",
    city: "Plymouth",
    province: "Minnesota",
    country: "US",
    website: "https://www.mnclay.com",
    bio: "Full-service pottery supply store serving Minnesota and the Upper Midwest with clay, glazes, tools, and kilns.",
  },
  // Mississippi
  {
    name: "Dogwood Ceramic Supply",
    city: "Gulfport",
    province: "Mississippi",
    country: "US",
    website: "https://www.dogwoodceramics.com",
    bio: "Gulf Coast ceramics supplier stocking clay, glazes, tools, and equipment for studio potters.",
  },
  // New Mexico
  {
    name: "New Mexico Clay",
    city: "Albuquerque",
    province: "New Mexico",
    country: "US",
    website: "https://nmclay.com",
    bio: "New Mexico's pottery supply store, carrying local and regional clay bodies, glazes, tools, and kiln equipment.",
  },
  // New York
  {
    name: "Bailey Pottery Equipment",
    city: "Kingston",
    province: "New York",
    country: "US",
    website: "https://www.baileypottery.com",
    bio: "Manufacturer and supplier of pottery wheels, kilns, and studio equipment, serving potters across North America.",
  },
  // North Carolina
  {
    name: "Starworks Ceramics",
    city: "Star",
    province: "North Carolina",
    country: "US",
    website: "https://www.starworksnc.org/ceramics",
    bio: "A North Carolina ceramics center offering supplies, studio space, and educational programs rooted in the region's clay traditions.",
  },
  // Ohio
  {
    name: "Columbus Clay Company",
    city: "Columbus",
    province: "Ohio",
    country: "US",
    website: "https://www.columbusclay.com",
    bio: "Ohio's full-service ceramics supplier, stocking clay bodies, glazes, tools, wheels, and kilns for all skill levels.",
  },
  // Oregon
  {
    name: "Georgie's Ceramic & Clay",
    city: "Portland",
    province: "Oregon",
    country: "US",
    website: "https://www.georgies.com",
    bio: "Portland's beloved ceramics supply store, carrying clay, glazes, tools, and studio equipment for over 40 years.",
  },
  // Pennsylvania
  {
    name: "The Ceramic Shop",
    city: "Norristown",
    province: "Pennsylvania",
    country: "US",
    website: "https://www.theceramicshop.com",
    bio: "Philadelphia-area pottery supply store stocking a wide range of clay, glazes, tools, and kiln equipment.",
  },
  // South Carolina
  {
    name: "Clay King",
    city: "Spartanburg",
    province: "South Carolina",
    country: "US",
    website: "https://www.clay-king.com",
    bio: "South Carolina ceramics supplier with an extensive selection of clay bodies, glazes, tools, wheels, and kilns.",
  },
  // Tennessee
  {
    name: "Mid-South Ceramic Supply",
    city: "Nashville",
    province: "Tennessee",
    country: "US",
    website: "https://midsouthceramics.com",
    bio: "Nashville's ceramics supply store, carrying clay, glazes, tools, and equipment for studio potters across the South.",
  },
  // Texas
  {
    name: "Armadillo Clay & Supplies",
    city: "Austin",
    province: "Texas",
    country: "US",
    website: "https://www.armadilloclay.com",
    bio: "Austin's full-service ceramics supplier, stocking clay bodies, glazes, tools, wheels, and kilns.",
  },
  {
    name: "Texas Pottery Supply & Clay Co.",
    city: "Fort Worth",
    province: "Texas",
    country: "US",
    website: "https://texaspottery.com",
    bio: "Texas-based pottery supply company carrying clay, glazes, and equipment for studio potters statewide.",
  },
  {
    name: "American Ceramic Supply Co.",
    city: "Carrollton",
    province: "Texas",
    country: "US",
    website: "https://americanceramics.com",
    bio: "North Texas ceramics supplier with a broad selection of clay bodies, glazes, tools, and kiln equipment.",
  },
  // Utah
  {
    name: "Capital Ceramics",
    city: "Salt Lake City",
    province: "Utah",
    country: "US",
    website: "https://www.capitalceramics.com",
    bio: "Utah's pottery supply store, carrying clay, glazes, tools, and kiln equipment for potters across the Intermountain West.",
  },
  // Washington
  {
    name: "Seattle Pottery Supply",
    city: "Seattle",
    province: "Washington",
    country: "US",
    website: "https://seattlepotterysupply.com",
    bio: "A Pacific Northwest institution stocking clay bodies, glazes, tools, and equipment since 1978.",
  },
  // Wisconsin
  {
    name: "The Potter's Shop",
    city: "Waukesha",
    province: "Wisconsin",
    country: "US",
    website: "https://www.pottersshop.com",
    bio: "Wisconsin ceramics supplier carrying clay, glazes, tools, and equipment for studio potters.",
  },
  // England
  {
    name: "Bath Potters' Supplies",
    city: "Bath",
    province: "England",
    country: "EU",
    website: "https://www.bathpotters.co.uk",
    bio: "A well-loved independent pottery supplier carrying clays, glazes, tools, and kilns.",
  },
  {
    name: "Potclays",
    city: "Stoke-on-Trent",
    province: "England",
    country: "EU",
    website: "https://www.potclays.co.uk",
    bio: "One of the UK's leading pottery suppliers, based in the heart of the Potteries.",
  },
  {
    name: "Clayman Supplies",
    city: "Horsham",
    province: "England",
    country: "EU",
    website: "https://www.claymansupplies.co.uk",
    bio: "Specialist pottery supplier offering clays, oxides, glazes, and kiln equipment across the UK.",
  },
  {
    name: "Hot Clay",
    city: "Somerset",
    province: "England",
    country: "EU",
    website: "https://hotclay.co.uk",
    bio: "Online pottery supplies and kilns shipped across the UK.",
  },
  // Queensland
  {
    name: "Pottery Supplies Online",
    city: "Brisbane",
    province: "Queensland",
    country: "AU",
    website: "https://www.potterysuppliesonline.com.au",
    bio: "Australia's online ceramic supply store, shipping clay, glazes, and tools nationwide.",
  },
  {
    name: "The Clay Shed",
    city: "Sunshine Coast",
    province: "Queensland",
    country: "AU",
    website: "https://theclayshed.com.au",
    bio: "Queensland-based ceramic supplies and workshops for studio potters.",
  },
  // New South Wales
  {
    name: "Keane Ceramics",
    city: "West Gosford",
    province: "New South Wales",
    country: "AU",
    website: "https://keaneceramics.com.au",
    bio: "Supplying Australian potters with clays, glazes, and kiln equipment since 1980.",
  },
  // Victoria
  {
    name: "Northcote Pottery Supplies",
    city: "Brunswick East",
    province: "Victoria",
    country: "AU",
    website: "https://northcotepottery.com",
    bio: "Melbourne's go-to ceramics supplier, carrying a wide range of clays, glazes, tools, and kilns.",
  },
];

export const teachingStudios: TeachingStudio[] = [
  // Ontario
  {
    name: "Clay With Me",
    city: "Toronto",
    province: "Ontario",
    country: "CA",
    website: "https://claywithme.ca",
    bio: "Courses, workshops, and private events for all skill levels, from beginner drop-in sessions to multi-week programs. Over 10 years in operation.",
  },
  {
    name: "Parkdale Pottery",
    city: "Toronto",
    province: "Ontario",
    country: "CA",
    website: "https://parkdalepottery.ca",
    bio: "Women-owned studio offering wheel throwing, handbuilding, and sculptural ceramics for beginners, kids, teens, and advanced students, plus private events.",
  },
  {
    name: "Spin Pottery",
    city: "Toronto",
    province: "Ontario",
    country: "CA",
    website: "https://spinpottery.com",
    bio: "Woman-owned downtown Toronto studio offering pottery classes and open studio memberships for all skill levels.",
  },
  {
    name: "The Pottery",
    city: "Toronto",
    province: "Ontario",
    country: "CA",
    website: "https://www.thepottery.ca",
    bio: "A studio, shop, and teaching space offering pottery lessons for adults and children in wheel throwing and handbuilding.",
  },
  {
    name: "Hintonburg Pottery",
    city: "Ottawa",
    province: "Ontario",
    country: "CA",
    website: "https://www.hintonburgpottery.ca",
    bio: "Ottawa's gathering place for pottery classes and workshops, offering beginner-to-intermediate wheel and handbuilding instruction for ages 12 and up.",
  },
  {
    name: "Play With Clay",
    city: "Cambridge",
    province: "Ontario",
    country: "CA",
    website: "https://playwithclaygalt.com",
    bio: "Pottery studio established in 2017 offering classes and workshops for all levels in the heart of Galt.",
  },
  // British Columbia
  {
    name: "Studio Fundamentals",
    city: "Vancouver",
    province: "British Columbia",
    country: "CA",
    website: "https://studiofundamentals.com",
    bio: "East Vancouver pottery studio offering beginner-friendly classes, multi-week courses, creative workshops, and studio memberships.",
  },
  {
    name: "Vancouver Ceramics Studio",
    city: "Vancouver",
    province: "British Columbia",
    country: "CA",
    website: "https://www.vancouverceramics.com",
    bio: "Community ceramics studio in South Vancouver offering wheel throwing and handbuilding workshops, six-week courses, and studio memberships.",
  },
  {
    name: "Community Clay",
    city: "Vancouver",
    province: "British Columbia",
    country: "CA",
    website: "https://www.communityclay.ca",
    bio: "Multi-week handbuilding pottery courses covering slab building, coiling, and sculpting for beginners and experienced artists alike.",
  },
  // Alberta
  {
    name: "Pottery123",
    city: "Calgary",
    province: "Alberta",
    country: "CA",
    website: "https://pottery123.com",
    bio: "Fully equipped community pottery studio offering adult classes from beginner to advanced levels.",
  },
  // New York
  {
    name: "Greenwich House Pottery",
    city: "New York",
    province: "New York",
    country: "US",
    website: "https://greenwichhouse.org/pottery",
    bio: "Founded in 1909, one of the oldest pottery schools in the US. Offers wheel throwing, handbuilding, mold making, and slipcasting across two Manhattan locations.",
  },
  // Pennsylvania
  {
    name: "The Clay Studio",
    city: "Philadelphia",
    province: "Pennsylvania",
    country: "US",
    website: "https://www.theclaystudio.org",
    bio: "One of the nation's most respected ceramics centres, offering classes, residencies, exhibitions, and education programs for all levels.",
  },
  // Illinois
  {
    name: "Lillstreet Art Center",
    city: "Chicago",
    province: "Illinois",
    country: "US",
    website: "https://lillstreet.com",
    bio: "Founded in 1975, offering 5- and 10-week ceramics classes alongside six other art disciplines for students 18 and up.",
  },
  // Washington D.C.
  {
    name: "District Clay Center",
    city: "Washington",
    province: "District of Columbia",
    country: "US",
    website: "https://www.districtclaycenter.com",
    bio: "The largest clay studio in the DC area with over 6,500 sq ft, offering 28+ weekly classes, artist residencies, a ceramic gallery, and community outreach programs.",
  },
  // California
  {
    name: "Berman Ceramic Arts",
    city: "Los Angeles",
    province: "California",
    country: "US",
    website: "https://www.bermanceramicarts.com",
    bio: "Established in 1972, the longest continuously operating studio in Los Angeles, offering wheel throwing, handbuilding, and contemporary sculpture classes.",
  },
  {
    name: "American Museum of Ceramic Art Studio",
    city: "Pomona",
    province: "California",
    country: "US",
    website: "https://www.amoca.org",
    bio: "Museum-based studio offering public ceramics classes alongside exhibition programming in Southern California.",
  },
  // Washington
  {
    name: "SPUN Clay Arts Studio",
    city: "Tacoma",
    province: "Washington",
    country: "US",
    website: "https://www.spuntacoma.com",
    bio: "All-ages, full-service studio in operation since 2014 providing creative and affordable pottery and handbuilding classes for all levels.",
  },
  // Maine
  {
    name: "Portland Pottery",
    city: "Portland",
    province: "Maine",
    country: "US",
    website: "https://portlandpottery.com",
    bio: "Established studio offering classes, workshops, and supplies in Maine and Massachusetts, with programs for all ages and skill levels.",
  },
  // England
  {
    name: "Turning Earth Ceramics",
    city: "London",
    province: "England",
    country: "EU",
    website: "https://www.turningearth.org",
    bio: "Pioneering open-access ceramics studios across three London locations, offering courses for all levels plus flexible studio membership — described as a gym membership for potters.",
  },
  // Scotland
  {
    name: "Edinburgh Ceramics Workshop",
    city: "Edinburgh",
    province: "Scotland",
    country: "EU",
    website: "https://www.edinburghceramicsworkshop.co.uk",
    bio: "Open-practice studio and teaching space offering drop-in sessions, memberships, masterclasses, and beginner and intermediate pottery courses.",
  },
  {
    name: "Clay Works Studios",
    city: "Dumfries",
    province: "Scotland",
    country: "EU",
    website: "https://clayworksstudios.co.uk",
    bio: "Fully equipped teaching studio in rural southwest Scotland offering pottery courses for everyone from beginners to seasoned professionals.",
  },
  // France
  {
    name: "Ateliers Terre & Feu",
    city: "Paris",
    province: "France",
    country: "EU",
    website: "https://www.terre-et-feu.com",
    bio: "Network of pottery studios across Paris and other French cities offering wheel throwing and ceramics courses at all levels.",
  },
  {
    name: "Dodo Toucan",
    city: "Paris",
    province: "France",
    country: "EU",
    website: "https://dodo-toucan.com",
    bio: "Paris ceramics studio offering trimester-based classes where students learn modelling, decoration, and glazing techniques in small groups.",
  },
  // Netherlands
  {
    name: "Art Ceramics Studio",
    city: "Amsterdam",
    province: "Netherlands",
    country: "EU",
    website: "https://www.artceramicsstudio.com",
    bio: "Amsterdam studio offering ceramics, Raku, and plaster mould-making courses open to the public.",
  },
  {
    name: "Hola Lola Studio",
    city: "Utrecht",
    province: "Netherlands",
    country: "EU",
    website: "https://www.holalolastudio.com",
    bio: "Utrecht pottery studio offering classes and workshops for all levels in a welcoming, contemporary setting.",
  },
  {
    name: "Studio Timmerman",
    city: "Rotterdam",
    province: "Netherlands",
    country: "EU",
    website: "https://studiotimmerman.com",
    bio: "Rotterdam-based ceramics studio inside a vibrant maker's building, offering handmade ceramics and pottery classes for beginners and beyond.",
  },
  // Italy
  {
    name: "La Meridiana",
    city: "Certaldo",
    province: "Italy",
    country: "EU",
    website: "https://lameridiana.fi.it",
    bio: "Well-regarded ceramics school offering intensive residential workshops and courses in a historic Tuscan setting.",
  },
  // Queensland
  {
    name: "Clayschool Brisbane",
    city: "Brisbane",
    province: "Queensland",
    country: "AU",
    website: "https://www.clayschool.com.au",
    bio: "Brisbane's longest-established pottery teaching studio, offering foundation courses and extended learning for beginners through to experienced artists.",
  },
  {
    name: "Crockd Studios",
    city: "Gold Coast",
    province: "Queensland",
    country: "AU",
    website: "https://studios.crockd.com",
    bio: "Pottery studios offering clay classes, beginner courses, and group events across multiple locations in New South Wales and Queensland.",
  },
  // Victoria
  {
    name: "Slow Clay Centre",
    city: "Melbourne",
    province: "Victoria",
    country: "AU",
    website: "https://www.slowclay.com",
    bio: "Specialist ceramic education centre established in 2012, known for teaching Japanese production-throwing techniques. All teachers are practicing exhibiting artists.",
  },
  {
    name: "Little Woods Studio",
    city: "Melbourne",
    province: "Victoria",
    country: "AU",
    website: "https://littlewoodsstudio.com.au",
    bio: "Community pottery and art studio run by Jesuit Social Services, open to the public and offering workshops in an inclusive, not-for-profit setting.",
  },
  // New South Wales
  {
    name: "The Pottery Shed",
    city: "Sydney",
    province: "New South Wales",
    country: "AU",
    website: "https://thepotteryshed.com.au",
    bio: "Sydney's original dedicated pottery school, conceived in 2010, offering affordable wheel-throwing classes for adults and children.",
  },
  {
    name: "ClayGround",
    city: "Sydney",
    province: "New South Wales",
    country: "AU",
    website: "https://www.clayground.com.au",
    bio: "Sydney's largest membership-focused eco-ceramic studio offering handbuilding and wheel-throwing courses, drop-in sessions, and firing services across two locations.",
  },
];

export function groupByProvince<T extends { province: string; country: Country }>(
  items: T[]
): { province: string; country: Country; items: T[] }[] {
  const map = new Map<string, T[]>();
  const sorted = [...items].sort((a, b) =>
    a.province.localeCompare(b.province)
  );
  for (const item of sorted) {
    const key = item.province;
    if (!map.has(key)) map.set(key, []);
    map.get(key)!.push(item);
  }
  return Array.from(map.entries()).map(([province, items]) => ({
    province,
    country: items[0].country,
    items: items.sort((a, b) => {
      const lastName = (n: string) => n.trim().split(" ").slice(-1)[0];
      const aName = "name" in a ? lastName((a as { name: string }).name) : "";
      const bName = "name" in b ? lastName((b as { name: string }).name) : "";
      return aName.localeCompare(bName);
    }),
  }));
}
